#!/usr/bin/env sh

# apps
super + {Return, shift + Return, alt + Return}
	{\
		~/.config/bspwm/context-run-urxvt.sh,\
		urxvt,\
		~/.config/bspwm/colored-urxvt.sh,\
	}

super + p ; {n, o, a, u, d, r}
	~/Projects/manage.fish {new, open, archive, unarchive, delete, run}

super + x ; { x, c, shift+v, v, shift+s, s, shift+n, n, alt+s, m, f, z, g, k}
	{\
		sh -c 'xcolor | xclip -sel clip',\
		chromium,\
		code,\
		context-run urxvt "code %F",\
		subl,\
		context-run urxvt "subl %F",\
		nautilus,\
		context-run urxvt "nautilus %F",\
		spotify,\
		flatpak run com.mattermost.Desktop,\
		chromium facebook.com/messages,\
		chromium youtube.com,\
		xset m 0 0; steam steam://rungameid/730,\
		~/birth.sh\
	}

shift + Menu
	systemctl --user is-active qmenu_hud && systemctl --user stop qmenu_hud || systemctl --user start qmenu_hud

Menu
	qmenu_hud

super + l; {p, l , r}
	systemctl {poweroff,suspend,reboot}


super + c; {n, shift + n, s, g}
	{\
		urxvt -e nmtui,\
		nm-connection-editor,\
		pavucontrol,\
		urxvt -e sh -c "pasuspender -- jackd -d alsa & guitarix"\
	}

super + space
	echo 'show' > /home/dbiro/Projects/All/Programming/vonal/VONALPIPE

shift + Print
	killall ffcast || ffcast -s byzanz-record --x=%x --y=%y --width=%w --height=%h ~/Pictures/recorded_region.gif

super + Print
	if [ $(pgrep xflux) ]; then killall xflux; else xflux -l 47.0963692 -g 17.9094899; fi

Print
	flameshot gui

#super + p
#	rofi-pass


# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# xf86 backlight
# super + XF86MonBrightnessUp
# 	/usr/bin/night inc
# super + XF86MonBrightnessDown
# 	/usr/bin/night dec

# xf86

XF86MonBrightnessUp
	intelbacklight -inc 10000
XF86MonBrightnessDown
	intelbacklight -dec 10000

XF86Calculator
	urxvt -e sage

XF86AudioPlay
	playerctl play-pause
XF86AudioNext
	playerctl next
XF86AudioPrev
	playerctl prev

XF86AudioLowerVolume
	pactl set-sink-volume @DEFAULT_SINK@ -10%
XF86AudioRaiseVolume
	pactl set-sink-volume @DEFAULT_SINK@ +10%
XF86AudioMute
	pactl set-sink-mute @DEFAULT_SINK@ toggle

alt + XF86AudioLowerVolume
	pactl set-source-volume @DEFAULT_SOURCE@ -10%

alt + XF86AudioRaiseVolume
	pactl set-source-volume @DEFAULT_SOURCE@ +10%

alt + XF86AudioMute
	pactl set-source-mute @DEFAULT_SOURCE@ toggle; if [ $(cat /sys/class/leds/input21::scrolllock/brightness) = 1 ]; then echo 0 > /sys/class/leds/input21::scrolllock/brightness ; else echo 1 > /sys/class/leds/input21::scrolllock/brightness ; fi


#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close/kill
super + {_,shift + }q
	bspc node -{c,k}

# close tab
super + w
	dash -c 'xdotool key ctrl+w'

# preselect
super + ctrl + {Left, Down, Up, Right}
	bspc node -p {west,south,north,east}

super + ctrl + {1-9}
	bspc node -o 0.{1-9};

super + ctrl + space
	bspc node -p cancel

# set the window state
super + {t,shift + t,s,m}
	bspc node -t {tiled,pseudo_tiled,floating,~fullscreen}

# focus the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the last node/desktop
super + Tab
	bspc desktop -f last

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}';

# rotate
super + {_,shift +}v
	set CURRENT (xdotool getwindowfocus); bspc node -f @parent; bspc node -R {90, -90}; xdotool windowactivate $CURRENT

# rotate workspace
super + alt + {_,shift +}v
	bspc node @/ -R {90, -90}

# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}
