#!/bin/bash

# Automatizations:
echo $HOME/.config/sxhkd/sxhkdrc | entr -np pkill -USR1 -x sxhkd & # Sxhkd
echo ./.Xresources | entr -n xrdb ./.Xresources & # X (for urxvt)

# Set the correct keyboard layout for sxhkd
setxkbmap -layout hu

# Start daemons:
systemctl --user reload-or-restart batwarn@"$DISPLAY".service # Brings the gamma up if the battery is low
systemctl --user reload-or-restart sxhkd@"$DISPLAY".service # Keyboard daemon (reloading keeps children)
systemctl --user reload-or-restart dunst@"$DISPLAY".service # Notification daemon
systemctl --user reload-or-restart flameshot@"$DISPLAY".service # Screenshot tool 
systemctl --user reload-or-restart kdeconnectd@"$DISPLAY".service # PC - Phone connection utility 
systemctl --user reload-or-restart vonal@"$DISPLAY".service # Application launcher
systemctl --user reload-or-restart gnome-polkit@"$DISPLAY".service # An app for authentication dialogs

# Handle multiple monitors:
#srandrd -n "$HOME/.config/bspwm/display_handler.sh"

autorandr --change

[ $(autorandr --current) = "default" ] && bspc monitor "DP-1-3" -d A B C D E F
[ $(autorandr --current) = "mobile" ] && bspc monitor "eDP-1" -d A B C D E F
[ $(autorandr --current) = "dock-nvidia" ] && bspc monitor "DP-1-1-3" -d A B C D E F
[ $(autorandr --current) = "mobile-nvidia" ] && bspc monitor "eDP-1-1" -d A B C D E F

# Set styles:
xsetroot -solid "#002"
xsetroot -cursor_name left_ptr
bspc config border_width         0
bspc config window_gap           5
bspc config top_padding          0
bspc config border_width       1
bspc config normal_border_color "#484848"
bspc config active_border_color "#888888"
bspc config focused_border_color "#1F8999"
bspc config presel_feedback_color "#1F8999"

# Set behaviour
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config single_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer       false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config external_rules_command "/home/dbiro/.config/bspwm/presentation_rule.sh"

# Set App specific rules
bspc rule -a Surf:surf state=tiled
bspc rule -a Vonal manage=off focus=on state=floating follow=on
bspc rule -a Steam desktop=5 split_dir=right follow=off state=tiled
bspc rule -a Sublime_text state=tiled
